#!/usr/bin/env bash
#Task /redirect_me to use redirection 301 to send to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "30i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=mUiazw80Lzo permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
