#!/usr/bin/env bash
# config nginx so thaht its HTTPS response contains a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "53i \\\t\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
