#!/usr/bin/env bash
# Executing the 100-process_and_pid_file script and killing it with ctrl+c.
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid; exit $?' SIGTERM
trap 'rm /var/run/holbertonscript.pid; exit $?' SIGQUIT
trap 'echo Y U no love me?!' SIGINT
echo $$ > /var/run/holbertonscript.pid
while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
