#!/usr/bin/env bash
#Steps to change the localhosts and the facebook.com IP address
cp /etc/hosts ~/changehosts
sed -i 's/127.0.0.1/127.0.0.2/g' ~/changehosts
echo "8.8.8.8 facebook.com" >> ~/changehosts
cp -f ~/changehosts /etc/hosts
